//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PANDA_MVC_V5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.PREGUNTA = new HashSet<PREGUNTA>();
            this.RESPUESTA = new HashSet<RESPUESTA>();
        }

        [Required(ErrorMessage = "El campo es requerido")]
        public string USERNAME { get; set; }
        [Required(ErrorMessage = "El campo es requerido")]
        public string NOMBRE { get; set; }
        [Required(ErrorMessage = "El campo es requerido")]
        public string APELLIDO { get; set; }
        [Required(ErrorMessage = "El campo es requerido")]
        public string DNI { get; set; }
        [Required(ErrorMessage = "El campo es requerido")]
        public string PAIS { get; set; }
        [Required(ErrorMessage = "El campo es requerido")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "El email no tiene el formato correcto")]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "El campo es requerido")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$", ErrorMessage = "Debe contener")]
        public string PASSWORD { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PREGUNTA> PREGUNTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPUESTA> RESPUESTA { get; set; }
    }
}
